# This is a reserved spot for most properties containing passwords or other secrets.
# Created by install at 2025-08-19T19:58:27.136177600Z

# Access to internal AES encryption key
idp.sealer.storePassword =Rnw4Sc5cE7mxXbYzDqyEGkPO6ylvQ+ih
idp.sealer.keyPassword =Rnw4Sc5cE7mxXbYzDqyEGkPO6ylvQ+ih

# Password for idp-backchannel.p12 
idp.backchannel.keyStorePassword =xJN0TPnAu2Xt60rO1Pb60YBEP4uBJo+y

# Default access to LDAP authn and attribute stores. 
idp.authn.LDAP.bindDNCredential              =myServicePassword
idp.attribute.resolver.LDAP.bindDNCredential =%{idp.authn.LDAP.bindDNCredential:undefined}

# Salt used to generate persistent/pairwise IDs, must be kept secret
#idp.persistentId.salt =changethistosomethingrandom
